/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xK0uUXk8TMe
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function Hero2() {
  return (
    <section className="relative w-full overflow-hidden">
      <div className="absolute inset-0 z-0">
        <img
          src="/placeholder.svg"
          width={1920}
          height={1080}
          alt="Hero Illustration"
          className="h-full w-full object-cover object-center"
        />
      </div>
      <div className="relative z-10 container py-32 md:py-40 lg:py-48">
        <div className="mx-auto max-w-3xl space-y-6 text-center">
          <h1 className="text-4xl font-bold tracking-tight text-primary-foreground sm:text-5xl lg:text-6xl">
            Secure and Reliable Cross-Chain Transfers
          </h1>
          <p className="text-xl text-muted-foreground md:text-2xl">
            StableBridge enables seamless and secure cross-chain transfers of stablecoins and other digital assets.
          </p>
          <Link
            href="#"
            className="inline-flex h-12 items-center justify-center rounded-md bg-primary px-6 text-base font-medium text-primary-foreground transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2 disabled:pointer-events-none disabled:opacity-50"
            prefetch={false}
          >
            Get Started
          </Link>
        </div>
      </div>
    </section>
  )
}
