/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YrQ28dEmshM
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function Stake() {
  return (
    <div className="bg-background rounded-lg border p-6 w-full max-w-md flex flex-col gap-6">
      <div className="flex flex-col gap-4">
        <div className="flex items-center justify-between">
          <h2 className="text-2xl font-bold">Staking</h2>
          <Link
            href="#"
            className="inline-flex items-center gap-2 rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
            prefetch={false}
          >
            <PlusIcon className="h-4 w-4" />
            Stake
          </Link>
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div className="bg-muted rounded-lg p-4 flex flex-col gap-2">
            <div className="text-sm text-muted-foreground">Staking Balance</div>
            <div className="text-2xl font-bold">12,345 STX</div>
          </div>
          <div className="bg-muted rounded-lg p-4 flex flex-col gap-2">
            <div className="text-sm text-muted-foreground">Stacking Rewards</div>
            <div className="text-2xl font-bold">1,234 STX</div>
          </div>
        </div>
      </div>
      <div className="flex flex-col gap-2">
        <Button variant="outline" className="w-full">
          Unstake
        </Button>
        <Button className="w-full">Claim Rewards</Button>
      </div>
    </div>
  )
}

function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}
