/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/gYizcDaU4UY
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Bricolage_Grotesque } from 'next/font/google'
import { Manrope } from 'next/font/google'

bricolage_grotesque({
  subsets: ['latin'],
  display: 'swap',
})

manrope({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Swap() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gradient-to-b from-[#1E293B] to-[#0F172A] text-white">
      <main className="w-full max-w-4xl p-6 md:p-10 bg-[#0F172A] rounded-2xl shadow-lg">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="flex flex-col gap-6">
            <div className="bg-[#1E293B] p-6 rounded-xl">
              <h2 className="text-2xl font-bold mb-4">Swap</h2>
              <div className="grid grid-cols-2 gap-4">
                <div className="flex flex-col gap-2">
                  <label htmlFor="from-amount" className="text-sm text-gray-400">
                    From
                  </label>
                  <div className="flex items-center bg-[#334155] rounded-lg px-4 py-2">
                    <input
                      id="from-amount"
                      type="number"
                      placeholder="0.0"
                      className="bg-transparent text-white w-full focus:outline-none"
                    />
                    <div className="text-sm text-gray-400">STX</div>
                  </div>
                </div>
                <div className="flex flex-col gap-2">
                  <label htmlFor="to-amount" className="text-sm text-gray-400">
                    To
                  </label>
                  <div className="flex items-center bg-[#334155] rounded-lg px-4 py-2">
                    <input
                      id="to-amount"
                      type="number"
                      placeholder="0.0"
                      className="bg-transparent text-white w-full focus:outline-none"
                    />
                    <div className="text-sm text-gray-400">BTC</div>
                  </div>
                </div>
              </div>
              <div className="flex justify-between items-center mt-4">
                <div className="text-sm text-gray-400">1 STX = 0.0001 BTC</div>
                <button className="bg-[#2563EB] hover:bg-[#1D4ED8] text-white font-medium py-2 px-4 rounded-lg transition-colors">
                  Swap
                </button>
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-6">
            <div className="bg-[#1E293B] p-6 rounded-xl">
              <h2 className="text-2xl font-bold mb-4">Your Balance</h2>
              <div className="flex items-center justify-between">
                <div>
                  <div className="text-sm text-gray-400">STX Balance</div>
                  <div className="text-2xl font-bold">10.5 STX</div>
                </div>
                <button className="bg-[#2563EB] hover:bg-[#1D4ED8] text-white font-medium py-2 px-4 rounded-lg transition-colors">
                  Connect Wallet
                </button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
